In [23]:
import pandas as pd

In [24]:
path = "Resources/data.csv"

data = pd.read_csv(path)

In [25]:
data.head()

,County,2020 Total Crash Fatalities,2020 Total Index Crimes Reported,"2020 Model-Based Estimate of Median Household Income, Dollars","2020 Average Weekly Wages, All Industries, Dollars",2020-21 Public Schools,2019 Public School CCRPI Score,"2020-21 Most Recent SAT Administration Average Scores, Combined",2019-20 ACT Composite Score,2016-2020 Mean Travel Time in Minutes,...,"2020 Votes Cast for President, Republican Party, Percent",2020 Total Persons in Poverty,2020 Unemployment Rate,median gross rent (2017 - 2021),median value of owner-occupied housing units (2017 - 2021),Est. Population,Avg_Temp,Max_Temp,Min_Temp,Percipitation
0,APPLING,6,179,"$44,871","$1,061",6,72.8,"1,019",19,44.9,...,78.30%,"3,550",4.70%,NaN,NaN,"18,470",66.4°F,77.9°F,54.9°F,"58.33"""
1,ATKINSON,1,91,"$39,633",$742,4,76.8,-,-,47.6,...,72.90%,"1,801",3.90%,NaN,NaN,"8,315",66.3°F,77.7°F,55.0°F,"57.63"""
2,BACON,4,186,"$41,756",$747,4,81.5,"1,019",-,42.3,...,86.10%,"2,261",4.60%,NaN,NaN,"11,280",66.2°F,77.5°F,55.0°F,"54.15"""
3,BAKER,3,0,"$43,696",$739,1,60.4,820,-,50.7,...,57.70%,701,6.00%,NaN,NaN,"3,250",66.8°F,77.2°F,56.4°F,"55.60"""
4,BALDWIN,11,"1,376","$49,350",$706,6,69.7,990,16,45.3,...,48.80%,"8,910",6.90%,NaN,NaN,"45,525",64.5°F,76.9°F,52.2°F,"50.43"""

In [30]:
df = data.query("County == 'CHEROKEE' | County == 'CLAYTON' | County == 'COBB' | County == 'DEKALB' | County == 'DOUGLAS' | County == 'FAYETTE' | County == 'FORSYTH' | County == 'FULTON' |County == 'GWINNETT' | County == 'HENRY' | County == 'ROCKDALE'")

atl_data = df.set_index(['County'])

atl_data

,2020 Total Crash Fatalities,2020 Total Index Crimes Reported,"2020 Model-Based Estimate of Median Household Income, Dollars","2020 Average Weekly Wages, All Industries, Dollars",2020-21 Public Schools,2019 Public School CCRPI Score,"2020-21 Most Recent SAT Administration Average Scores, Combined",2019-20 ACT Composite Score,2016-2020 Mean Travel Time in Minutes,"2020 Votes Cast for President, Democratic Party, Percent","2020 Votes Cast for President, Republican Party, Percent",2020 Total Persons in Poverty,2020 Unemployment Rate,median gross rent (2017 - 2021),median value of owner-occupied housing units (2017 - 2021),Est. Population,Avg_Temp,Max_Temp,Min_Temp,Percipitation
County,,,,,,,,,,,,,,,,,,,,
CHEROKEE,21,"1,275","$90,675",$863,37,83.4,"1,129",22,67.7,29.50%,68.80%,"17,630",4.80%,"$1,421","$292,300","235,895",60.5°F,71.3°F,49.6°F,"58.11"""
CLAYTON,49,"9,361","$49,370","$1,200",66,62.4,977,17,62.1,85.00%,14.10%,"48,136",10.30%,"$1,100","$136,600","274,150",63.3°F,73.9°F,52.6°F,"51.23"""
COBB,85,"13,515","$81,517","$1,259",110,86.1,"1,144",23,61.6,56.30%,42.00%,"69,097",5.90%,"$1,367","$293,800","739,070",61.9°F,72.7°F,51.2°F,"54.20"""
DEKALB,92,"23,451","$69,545","$1,217",131,75.4,"1,100",20,32.0,83.10%,15.70%,"118,345",7.90%,"$1,312","$255,600","736,065",62.6°F,73.4°F,51.9°F,"52.41"""
DOUGLAS,13,"3,464","$65,269",$859,35,75.9,"1,038",19,33.7,62.00%,36.80%,"16,770",7.30%,"$1,194","$182,300","140,150",62.2°F,73.1°F,51.2°F,"57.63"""
FAYETTE,6,"1,359","$98,623",$952,24,89.5,"1,154",23,32.2,45.90%,52.70%,"6,079",5.30%,"$1,482","$309,300","110,305",63.3°F,74.1°F,52.5°F,"49.96"""
FORSYTH,12,"1,231","$116,690","$1,030",41,92.7,"1,178",25,33.1,32.60%,65.80%,"12,669",4.50%,"$1,619","$385,600","211,300",60.4°F,71.3°F,49.5°F,"55.72"""
FULTON,145,"13,581","$71,504","$1,641",110,83.8,"1,098",24,28.9,72.60%,26.20%,"136,220",7.90%,"$1,367","$345,100","1,010,420",62.3°F,73.1°F,51.6°F,"53.24"""
GWINNETT,57,285,"$61,071",$785,14,80.9,"1,107",26,53.3,17.40%,81.40%,"5,963",5.40%,"$1,414","$256,700","43,880",59.6°F,70.1°F,49.1°F,"67.84"""
HENRY,28,"2,169","$69,442",$962,37,83.1,"1,096",21,22.4,43.10%,55.50%,"17,041",5.20%,"$1,194","$182,300","150,340",65.4°F,77.4°F,53.4°F,"52.48"""
ROCKDALE,17,18,"$53,163",$738,2,80.8,"1,190",20,51.8,20.30%,79.10%,779,4.30%,"$1,156","$174,600","5,170",64.9°F,76.0°F,53.7°F,"54.69"""

In [31]:
weather_data = atl[['Avg_Temp', 'Max_Temp', 'Min_Temp', 'Percipitation']]

weather_data

         Avg_Temp Max_Temp Min_Temp Percipitation
County
CHEROKEE   60.5°F   71.3°F   49.6°F        58.11"
CLAYTON    63.3°F   73.9°F   52.6°F        51.23"
COBB       61.9°F   72.7°F   51.2°F        54.20"
DEKALB     62.6°F   73.4°F   51.9°F        52.41"
DOUGLAS    62.2°F   73.1°F   51.2°F        57.63"
FAYETTE    63.3°F   74.1°F   52.5°F        49.96"
FORSYTH    60.4°F   71.3°F   49.5°F        55.72"
FULTON     62.3°F   73.1°F   51.6°F        53.24"
GWINNETT   59.6°F   70.1°F   49.1°F        67.84"
HENRY      65.4°F   77.4°F   53.4°F        52.48"
ROCKDALE   64.9°F   76.0°F   53.7°F        54.69"

In [32]:
# export
atl_data.to_csv('Resources/atl_data.csv', index=True)
weather_data.to_csv('Resources/weather_data.csv', index=True)